### PR TITLE
[AMORO-1871]Support register paimon catalog

### LINKED ISSUE #1871: [Subtask]: Support registering for the Paimon Catalog.
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### Description

Support registering for the Paimon Catalog.

### Parent issue

#1269 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by shidayang**
## Why are the changes needed?
Close #1871.

## Brief change log
1. Add paimon format option in catalog page

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zhoujinsong** [comment]
As the project name have changed from `Arctic` to `Amoro`, we should change the prefix of PR title to `[AMORO-1871]`.

**Comment by baiyangtx** [comment]
Should this PR be merged after https://github.com/NetEase/amoro/pull/1960 is merged?

**Comment by shidayang** [comment]
> Should this PR be merged after #1960 is merged?
> 
> Can we turn it into a draft first?

Need after #1960 .

**Comment by baiyangtx** [comment]
> > Should this PR be merged after #1960 is merged?
> > Can we turn it into a draft first?
> 
> Need after #1960 . There's no need to set it as a draft.

If your PR is still in process and not ready for review, you should turn it to draft. so that we will not recive the notification email when you push new commits.

**Comment by shidayang** [comment]
image

**Review by baiyangtx — APPROVED** [review]
LGTM, thanks for your contribution.

**Pull request merged**
