### PR TITLE
[CI] Limit concurrency of workflow

### PR DESCRIPTION
**Pull request by GOODBOY008**
Limit concurrency of workflow to reduce task queuing in GitHub Actions.

### CODE REVIEW

**Comment by GOODBOY008** [comment]
J`PS{WUJDOJYB`0UR0VJOBF
@shidayang PTAL.

**Comment by baiyangtx** [comment]
Can you describe the context of this PR? What problem is it trying to solve? What approach is used to address the issue?

**Comment by GOODBOY008** [comment]
Hi @baiyangtx, Limit concurrency of workflow to reduce task queuing in GitHub Actions. When our contributors append commits in a  pr and github action will excute many times until end  ,this will make ci task queuing  . So I want to cancel previous ci task and run latest commit's ci task. As the upper screenshot  shows.

**Comment by baiyangtx** [comment]
@zhoujinsong PTAL

**Comment by shidayang** [comment]
Very useful work. LGTM

**Review by shidayang — APPROVED** [review]

**Pull request merged**
