### PR TITLE
[AMORO-2012]Bump up some dependencies' versions

### PR DESCRIPTION
**Pull request by zhoujinsong**
## Why are the changes needed?

This is a part of the work for #2012 aiming at bumping some dependencies' versions to enhance the security of the project.

## Brief change log

- Bump up `org.mockito:mockito-core` to 4.11.0 and it is the latest version that supports JDK8.
- Drop `org.powerpock:powermock-api-mockito2` dependency as mockito has supported mocking static method in 4.x.
- Bump up `org.apache.commons:commons-pool` to 2.12.0
- Bump up `org.apache.curator:curator-framework` to 5.6.0
- Bump up `org.apache.zookeeper:zookeeper` to 3.9.1
- Bump up `com.github.ben-manes.caffeine:caffeine` to 2.9.3 and it is the latest version that supports JDK8.
- Bump up `com.esotericsoftware:kyro` to 4.0.3
- Bump up `org.apache.common:commons-lang3` to 3.14.0
- Bump up `org.roaringbitmap:RoaringBitmap` to 1.0.1
- Bump up `org.apache.common:commons-pool2` to 2.12.0
- Bump up aws related packages to 2.24.12
- Bump up `org.mybatis:mybatis` to 3.5.15
- Bump up `org.apache.derby:derby` to 10.14.2.0 and it is the latest version that supports JDK8.
- Bump up `org.postgresql:postgresql` to 42.7.2

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by czy006** [comment]
@zhoujinsong apache curator version is 5.2.1, If we change the zk version, We need to pay attention to whether high availability will be affected

**Comment by zhoujinsong** [comment]
> @zhoujinsong apache curator version is 5.2.1, If we change the zk version, We need to pay attention to whether high availability will be affected

Hi, I bumped up `org.apache.curator:curator-framework` to 5.6.0 and curator 5.6.0 dependent on zookeeper 3.7.2. 
I will test the high availability before merging.

**Comment by zhoujinsong** [comment]
I tested it in my local and hadoop 2.10.2 environment and it works fine.

**Review by zhongqishang — APPROVED** [review]
I tested it in my local ams and hadoop 2.6.0 environment and it works fine.
LGTM.

**Comment by shendanfengg** [comment]
I tested it in my local ams and hadoop 2.9.1 environment and it works fine.
I also tested the high availability feature, and it works。

**Comment by zhoujinsong** [comment]
> I tested it in my local ams and hadoop 2.9.1 environment and it works fine. I also tested the high availability feature, and it works.

Thanks a lot for your review and validation.

**Pull request merged**
