### PR TITLE
[Arctic-1317][Imporvement]: Make IDEAL java codestyle file match the maven codestyle check.

### LINKED ISSUE #1317: [Improvement]: Make IDEA java style match codestyle check
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently the `style/idea/intellij-java-palantir-style.xml` dosen't match the maven codestyle check rules.

### How should we improve?

1. Adjust the idea codestyle rules to match maven codestyle check.
2. Save the idea-java-style rule file to `.idea/codeStyle` folder and add to git trace

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by baiyangtx**
## Why are the changes needed?

fix #1317 

## Brief change log

- Export adjusted ideal codestyle file and replace the current codestyle file.

### CODE REVIEW

**Comment by zhoujinsong** [comment]
hi, could you first explain the specific problem that the original configuration file does not match the checkstyle?

**Comment by baiyangtx** [comment]
> hi, could you first explain the specific problem that the original configuration file does not match the checkstyle?

yes, the currently `style/idea/intellij-java-palantir-style.xml` doesn't contain any java style config setting.

**Review by zhoujinsong — COMMENTED** [review]
This change seems to have removed many rules, but I prefer to modify the rules that do not meet expectations or add new rules.

**Comment by pan3793** [comment]
The checkstyle does not have corresponding auto-fix tools. Combining "spotless" w/ "google java format" should be the easiest way.

**Comment by baiyangtx** [comment]
Using spotless instead.

**Pull request closed without merging**
