### PR TITLE
[AMORO-1070][Fix] Support comments in terminal

### LINKED ISSUE #1070: [Imporvement]: Arctic Terminal not support comments `#`
### What happened?

When I write a comment with `#` in Arctic Terminal, it doesn't work.

However, `--` and `/*  */` work.

### Affects Versions

master/0.4.0/

### What engines are you seeing the problem on?

AMS

### How to reproduce

Type to Terminal like 
```
# comment
insert into test.table124 values (4,3)
```

### Relevant log output

_No response_

### Anything else

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chenyuzhi459**
## Why are the changes needed?

Close #1070.

## Brief change log

-  Support comment with # in Arctic Terminal,

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

image

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? ( no)
- If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Review by shidayang — APPROVED** [review]

**Comment by shidayang** [comment]
LGTM

**Review by HuangFru — COMMENTED** [review]
Thanks for your contribution.
When it is recognized as a comment, the front end will display the line semi-transparently. Currently '--' can be recognized, but '#' cannot. Are you interested in implementing it with the front end?

**Comment by chenyuzhi459** [comment]
> Thanks for your contribution. When it is recognized as a comment, the front end will display the line semi-transparently. Currently '--' can be recognized, but '#' cannot. Are you interested in implementing it with the front end?

Yes, I'd like provide a front-end implementation to provide a complete improvement, but I am not very familiar with the front-end. I tried to change the  [`sql.ts` file](https://github.com/NetEase/amoro/blob/0a2f54a231f64eebfb691e5e75e729af2b8f5aa6/ams/dashboard/src/utils/sql.ts#L22) in my latest  code commit , but after compilation, the effect of the comments was still not achieved.

 If could get some suggestions or tips，it would be appreciated.

**Comment by wangtaohz** [comment]
> Yes, I'd like provide a front-end implementation to provide a complete improvement, but I am not very familiar with the front-end. I tried to change the [sql.ts file](https://github.com/NetEase/amoro/blob/0a2f54a231f64eebfb691e5e75e729af2b8f5aa6/ams/dashboard/src/utils/sql.ts#L22) in my latest code commit , but after compilation, the effect of the comments was still not achieved.
If could get some suggestions or tips，it would be appreciated.

You need to build the static file after changing the code of front-end, follow the steps:
```
cd ams/dashboard
npm run build
```
However, this requires you to do some front-end environment configuration locally, following `ams/dashboard/README.md`.
If you have difficulty, I can help you complete this step.

**Comment by HuangFru** [comment]
> > Thanks for your contribution. When it is recognized as a comment, the front end will display the line semi-transparently. Currently '--' can be recognized, but '#' cannot. Are you interested in implementing it with the front end?
> 
> Yes, I'd like provide a front-end implementation to provide a complete improvement, but I am not very familiar with the front-end. I tried to change the [`sql.ts` file](https://github.com/NetEase/amoro/blob/0a2f54a231f64eebfb691e5e75e729af2b8f5aa6/ams/dashboard/src/utils/sql.ts#L22) in my latest code commit , but after compilation, the effect of the comments was still not achieved.
> 
> If could get some suggestions or tips，it would be appreciated.
> 
> @HuangFru

You can get some relevant information from the README in the dashboard directory. I've made a little summary of what you're trying to do:
1. Modify the relevant code of the front end (you have already done it).
2. Install the front-end environment according to the README. Personally (I am also not very familiar with the front-end), I have only succeeded in my current environment version, so it is recommended that you use the following versions (mainly focusing on the major versions):image

3. Execute the `yarn run build` command in the dashborad directory to build the front-end code. Then you will get some front-end resource code.  

After the front-end build is successful, package and test the project. After the test is successful, the resource files and codes generated by the front-end build need to be submitted.

**Comment by chenyuzhi459** [comment]
Well, I have built and run fron-end locally(connecting with local ams server, using vue),  but when logined using v,  it got an error with msg `need login before request`. It looks like the sessionContext was wrong. However, when I logined directly using the http-server port `1630`, it' doesn't have the same problem.

It confued me !

The sever log:
image

The front-end：
image


The deepest cause I can found in the code:
image

**Comment by wangtaohz** [comment]
> Well, I have built and run fron-end locally(connecting with local ams server, using vue), but when logined using v, it got an error with msg need login before request. It looks like the sessionContext was wrong. However, when I logined directly using the http-server port 1630, it' doesn't have the same problem.
It confued me !

Yes, it also confused me. As a temporary method for local debugging, you can just make this method return `false` and skip the check.

image

@minteliuwm @lpdong Do you have any experience to solve this problem?

**Comment by chenyuzhi459** [comment]
> Yes, it also confused me. As a temporary method for local debugging, you can just make this method return `false` and skip the check.

Well, thanks for your tips, it works! 

However, it looks like it not supported specifying multiple ways for single line comments in `Monaco` editor 。

Related Links:
https://github.com/Microsoft/monaco-editor/issues/937

**Comment by wangtaohz** [comment]
> However, it looks like it not supported specifying multiple ways for single line comments in Monaco editor 。
>
>Related Links:
>https://github.com/microsoft/monaco-editor/issues/937

Okay, using `#` as a single-line comment may not be a very popular form. I think it's okay to only support it in the backend and revert the code of the front end.

**Review by wangtaohz — APPROVED** [review]
LGTM!

**Review by HuangFru — APPROVED** [review]
LGTM.

**Pull request merged**
