### PR TITLE
[AMORO-2401] Support reading encrypted iceberg data files

### LINKED ISSUE #2401: [Feature]: Support reading encrypted iceberg data files
### Description

When ever reading and writing data file, iceberg use a module call `EncryptionManager` to encrypt/decrypt files.

As for Amoro's implementation for reading iceberg data file, is does not do the decryption, which lead to reading failed if the table has been encrypted.

### Use case/motivation

As the description above, iceberg data file should be decrypted before reading

### Describe the solution

After opening iceberg data file, use `EncryptionManager` to decrypt those file before reading.

### Subtasks

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liaoyt**
## Why are the changes needed?

Close #2401.

## Brief change log

- As described in #2401

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by zhoujinsong** [comment]
@liaoyt Thanks a lot for your contribution!

You may need to sign NetEase's CLA before you start to contribute to Amoro, you can conveniently complete the signing via the link: https://cla-assistant.io/NetEase/amoro

**Comment by liaoyt** [comment]
> @liaoyt Thanks a lot for your contribution!
> 
> You may need to sign NetEase's CLA before you start to contribute to Amoro, you can conveniently complete the signing via the link: https://cla-assistant.io/NetEase/amoro

thanks for reminding, already signed

**Comment by shidayang** [comment]
@liaoyt Thanks for your contribution，I want to know if you are currently using the encryption feature.

**Comment by liaoyt** [comment]
> @liaoyt Thanks for your contribution，I want to know if you are currently using the encryption feature.

yes, although iceberg has only `PlaintextEncryptionManager` currently, we implement a custom encryption manager

**Comment by shidayang** [comment]
> > @liaoyt Thanks for your contribution，I want to know if you are currently using the encryption feature.
> 
> yes, although iceberg has only `PlaintextEncryptionManager` currently, we implement a custom encryption manager

I am very interested in this area. How does your EncryptionManager work? Currently, the implementation of BaseTable does not provide a custom method. Did you wrap your own Table object?

**Comment by liaoyt** [comment]
> > > @liaoyt Thanks for your contribution，I want to know if you are currently using the encryption feature.
> > 
> > 
> > yes, although iceberg has only `PlaintextEncryptionManager` currently, we implement a custom encryption manager
> 
> I am very interested in this area. How does your EncryptionManager work? Currently, the implementation of BaseTable does not provide a custom method. Did you wrap your own Table object?

There is not custom method provided currently, we just overwrite the `TableOperations.encryption()` method to provider our custom `EncryptionManager`.
Also, we patch some of the PR in this project: https://github.com/apache/iceberg/projects/5

**Comment by liaoyt** [comment]
As for the behavior of reading data file of iceberg table, iceberg already implement it. This PR attempt to keep this behavior the same as iceberg do.

**Comment by shidayang** [comment]
> > > > @liaoyt Thanks for your contribution，I want to know if you are currently using the encryption feature.
> > > 
> > > 
> > > yes, although iceberg has only `PlaintextEncryptionManager` currently, we implement a custom encryption manager
> > 
> > 
> > I am very interested in this area. How does your EncryptionManager work? Currently, the implementation of BaseTable does not provide a custom method. Did you wrap your own Table object?
> 
> There is not custom method provided currently, we just overwrite the `TableOperations.encryption()` method to provider our custom `EncryptionManager`. Also, we patch some of the PR in this project: https://github.com/apache/iceberg/projects/5

I got you, BTW, GenericDeleteFilter also need EncryptionManager

**Comment by liaoyt** [comment]
> > > > > @liaoyt Thanks for your contribution，I want to know if you are currently using the encryption feature.
> > > > 
> > > > 
> > > > yes, although iceberg has only `PlaintextEncryptionManager` currently, we implement a custom encryption manager
> > > 
> > > 
> > > I am very interested in this area. How does your EncryptionManager work? Currently, the implementation of BaseTable does not provide a custom method. Did you wrap your own Table object?
> > 
> > There is not custom method provided currently, we just overwrite the `TableOperations.encryption()` method to provider our custom `EncryptionManager`. Also, we patch some of the PR in this project: https://github.com/apache/iceberg/projects/5
> 
> I got you, BTW, GenericDeleteFilter also need EncryptionManager

thanks for reminding, i'll have a look and fix it later, maybe tomorrow.

**Comment by shidayang** [comment]
Can you add some unit tests to verify if it's working?

**Comment by liaoyt** [comment]
> Can you add some unit tests to verify if it's working?

sure，i can try add some unit test

**Review by shidayang — APPROVED** [review]
LGTM

**Comment by shidayang** [comment]
Thanks for your contributions

**Pull request merged**
