### PR TITLE
[AMORO-2032]: Spark3.2 version does not require the class ResolveProcedures

### LINKED ISSUE #2032: [Bug]: Spark SQL using amoro spark runtime error class cannot find ResolveProcedures
### What happened?

I added the amoro spark-3.2-runtime-0.5.0.jar package to the jars directory of Spark. When starting using SparkSQL, an error was reported and the class was not found: java. lang. NoClassDefFoundError: com/netease/arc/shadow/org/apache/Spark/sql/catalyst/analysis/ResolveProcedures
image
image

### Affects Versions

0.5.0

### What engines are you seeing the problem on?

Spark

### How to reproduce

Should I still want to add which dependency package, or in https://amoro.netease.com/download/. The package inside needs to be recompiled

### Relevant log output

```shell
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/netease/arctic/shade/org/apache/spark/sql/catalyst/analysis/ResolveProcedures
	at com.netease.arctic.spark.ArcticSparkExtensions.apply(ArcticSparkExtensions.scala:51)
	at com.netease.arctic.spark.ArcticSparkExtensions.apply(ArcticSparkExtensions.scala:31)
	at org.apache.spark.sql.SparkSession$.$anonfun$applyExtensions$1(SparkSession.scala:1197)
	at org.apache.spark.sql.SparkSession$.$anonfun$applyExtensions$1$adapted(SparkSession.scala:1192)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$applyExtensions(SparkSession.scala:1192)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:956)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLEnv$.init(SparkSQLEnv.scala:54)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.<init>(SparkSQLCLIDriver.scala:328)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:160)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NoClassDefFoundError: com/netease/arctic/shade/org/apache/spark/sql/catalyst/analysis/ResolveProcedures
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bdxmq**
## Why are the changes needed?

When using amoro spark-3.2-runtime-0.5.0.jar, an error was reported and the class ResolveProcedures could not be found. Through comparison, it was found that changing the class is no longer necessary. Simply remove the dependency of this class.
Close #2032 .

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? ( no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by baiyangtx** [comment]
Can you provide a screenshot of using the packaged runtime.jar in the Spark engine? It's because unit tests for the Spark module don't test whether shade is reasonable or not.

**Comment by wangtaohz** [comment]
Thanks for your contribution! 👍 @bdxmq 

It looks like a miss for Spark 3.2. 

If you verify it successfully in your enviromnent, we can merge it and consider including it in version 0.5.1.

**Comment by bdxmq** [comment]
I removed this line of code locally, packaged it, and used Spark SQL to use queries normally
image

**Review by wangtaohz — APPROVED** [review]
LGTM!

**Review by baiyangtx — APPROVED** [review]
LGTM, thanks for you contribution.

**Pull request merged**
