### PR TITLE
[AMORO-2154] Remove redundant whitespace characters

### LINKED ISSUE #2154: [DOC][hotfix] Remove redundant whitespace characters
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Fix spelling mistakes in table-watemark.md and using-table.md.

'table.event-time-field ' = 'op_time'     => 'table.event-time-field' = 'op_time'

### How should we improve?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by tcodehuber**
## Why are the changes needed?

Close #2154.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by HuangFru — COMMENTED** [review]
Thanks for your contribution. Since the Arctic has been renamed to Amoro, You need to change the PR's title to 'AMORO-2154' and follow community norms to write 'fix #2154' under 'Why are the changes needed?' content.

**Comment by tcodehuber** [comment]
> Thanks for your contribution. Since the Arctic has been renamed to Amoro, You need to change the PR's title to 'AMORO-2154' and follow community norms to write 'fix #2154' under 'Why are the changes needed?' content.

done.

**Review by wangtaohz — APPROVED** [review]
LGTM! Thank you for your contribution. 

BTW, if the PR is simple and clear enough, it's ok not creating a related issue. 😊

**Comment by tcodehuber** [comment]
> LGTM! Thank you for your contribution.
> 
> BTW, if the PR is simple and clear enough, it's ok not creating a related issue. 😊

Copy that.

**Pull request merged**
