### PR TITLE
[AMORO-2542] Fix Using `transform` partition and the partition value is `null`, the problem of `optimizing` cannot be triggered

### LINKED ISSUE #2542: [Bug]: partition values is `null` ​​will not trigger `Optimizing`
### What happened?

image
For example, if I set the partition mode to `transform` and my data value is null, `Optimizing` will not be triggered at this time.

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### How to reproduce

_No response_

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by huyuanfeng2018**
## Why are the changes needed?

Close #2542 .

## Brief change log

- Add detection to avoid throwing exceptions in `org.apache.iceberg.expressions`

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by HuangFru — APPROVED** [review]
LGTM.

**Comment by huyuanfeng2018** [comment]
> @huyuanfeng2018 The codes look good to me, do you think we should add some unit test case about it?

Of course, but there is a problem here is that there is no `optional` column defined in the `BasicTableTestHelper.TABLE_SCHEMA` definition, so if I want to modify this scenario, I need to define an optional column, which involves many other test cases. Do you think it’s appropriate to add these to this PR?

**Comment by XBaith** [comment]
> Of course, but there is a problem here is that there is no `optional` column defined in the `BasicTableTestHelper.TABLE_SCHEMA`

Maybe you can define a new table schema in `TestUnkeyedExpressionUtil` and `TestKeyedExpressionUtil`?

**Comment by huyuanfeng2018** [comment]
> @huyuanfeng2018 The codes look good to me, do you think we should add some unit test case about it?

done.

**Comment by huyuanfeng2018** [comment]
> > Of course, but there is a problem here is that there is no `optional` column defined in the `BasicTableTestHelper.TABLE_SCHEMA`
> 
> Maybe you can define a new table schema in `TestUnkeyedExpressionUtil` and `TestKeyedExpressionUtil`?

done.

**Review by XBaith — APPROVED** [review]
LGTM

**Pull request merged**
