### PR TITLE
fix spellings and typo

### PR DESCRIPTION
**Pull request by iamahens**
This pull request addresses and corrects grammatical and spelling errors throughout the codebase to improve code readability.
The changes include fixing typos, punctuation, and ensuring proper sentence structure without introducing functional modifications.
These updates are intended to enhance the quality of documentation and code comments.
The focus is on making the codebase more polished and user-friendly by eliminating language-related issues.

### CODE REVIEW

**Comment by iamahens** [comment]
@wangtaohz please review !

**Comment by wangtaohz** [comment]
Thanks for your work!  👍 

But I think `index-bakl.vue` is an deprecated file (the current file in use is `index.vue`), and we can delete this deprecated file directly in this PR.

BTW, are you interested in participating in the frontend development of Amoro?  There are some frontend issues that can help you start contributing to the community.

**Comment by baiyangtx** [comment]
If the `index-bakl.vue` is an deprecated file, I think we can delete it in this PR  @wangtaohz @iamahens

**Comment by baiyangtx** [comment]
@iamahens  Are you still working on this PR?

**Pull request closed without merging**
