### PR TITLE
[HOTFIX] Update metric-reporters.yaml

### PR DESCRIPTION
**Pull request by tcodehuber**
## Why are the changes needed?

Commenting out this part of the configuration will cause an error when starting AMS：
`throw new IllegalArgumentException("map is null.");`

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by baiyangtx — CHANGES_REQUESTED** [review]
I suggest modifying the code to be compatible with situations where there is no plugin config.yaml or where the file is empty because the plugin is not necessarily needed.

**Comment by tcodehuber** [comment]
> I suggest modifying the code to be compatible with situations where there is no plugin config.yaml or where the file is empty because the plugin is not necessarily needed.

OK, I will try it

**Comment by zhoujinsong** [comment]
> OK, I will try it

@tcodehuber Thank you very much for raising and trying to fix this issue. I also agree that making the code adaptable to the absence of this configuration is a better solution. Could you please update me on the current progress of the solution? Also, feel free to reach out to me if there are any implementation issues.

**Comment by tcodehuber** [comment]
@zhoujinsong 
I will commit the code this weekend.

**Comment by tcodehuber** [comment]
> > OK, I will try it
> 
> @tcodehuber Thank you very much for raising and trying to fix this issue. I also agree that making the code adaptable to the absence of this configuration is a better solution. Could you please update me on the current progress of the solution? Also, feel free to reach out to me if there are any implementation issues.

https://github.com/NetEase/amoro/pull/2512

**Pull request closed without merging**
