### PR TITLE
[AMORO-2056] Replace commandline banner from `Javalin` to `Amoro`

### LINKED ISSUE #2056: [Improvement]: Replace commandline banner from `Javalin` to `Amoro`
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently,  A Javalin banner is printed when AMORO start up,  maybe we shoud replace it with an AMORO banner?

```
2023-10-01 03:03:29,406 INFO [main] [org.eclipse.jetty.util.log] [] - Logging initialized @3275ms to org.eclipse.jetty.util.log.Slf4jLog
2023-10-01 03:03:29,506 INFO [main] [io.javalin.Javalin] [] - 
       __                      __ _            __ __
      / /____ _ _   __ ____ _ / /(_)____      / // /
 __  / // __ `/| | / // __ `// // // __ \    / // /_
/ /_/ // /_/ / | |/ // /_/ // // // / / /   /__  __/
\____/ \__,_/  |___/ \__,_//_//_//_/ /_/      /_/

          https://javalin.io/documentation

2023-10-01 03:03:29,507 INFO [main] [io.javalin.Javalin] [] - Starting Javalin ...
2023-10-01 03:03:29,511 INFO [main] [io.javalin.Javalin] [] - You are running Javalin 4.6.1 (released June 5, 2022. Your Javalin version is 482 days old. Consider checking for a newer version.).
```

### How should we improve?

I found a font pretty nice, maybe we could use this.

```
    ___     __  ___   ____     ____    ____ 
   /   |   /  |/  /  / __ \   / __ \  / __ \
  / /| |  / /|_/ /  / / / /  / /_/ / / / / /
 / ___ | / /  / /  / /_/ /  / _, _/ / /_/ / 
/_/  |_|/_/  /_/   \____/  /_/ |_|  \____/  
                                            
```
https://manytools.org/hacker-tools/ascii-banner/#google_vignette
font: slant

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongqishang**
## Why are the changes needed?

Close #2056.

## Brief change log

Via https://manytools.org/hacker-tools/ascii-banner/#google_vignette
Font: slant
Horizontal spacing: Normal
Vertical spacing: Fitted

- Disable `showJavalinBanner`
- Add log print

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

```
14:48:31,639 INFO  com.netease.arctic.server.ArcticServiceContainer             [] - 
    ___     __  ___ ____   ____   ____ 
   /   |   /  |/  // __ \ / __ \ / __ \
  / /| |  / /|_/ // / / // /_/ // / / /
 / ___ | / /  / // /_/ // _, _// /_/ / 
/_/  |_|/_/  /_/ \____//_/ |_| \____/  
                                       
      https://amoro.netease.com/       
 
```
## Documentation

- Does this pull request introduce a new feature? (yes / **no**)
- If yes, how is the feature documented? (**not applicable** / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by HuangFru — COMMENTED** [review]
It feels a little bit strange just for me that the slope of the letter A is not the same as the slope of the other letters.

**Comment by zhongqishang** [comment]
> It feels a little bit strange just for me that the slope of the letter A is not the same as the slope of the other letters.

The slope of all characters is the same, A will be visually different. 😂

```
    ___ 
   /   |
  / /| |
 / ___ |
/_/  |_|
    __  ___
   /  |/  /
  / /|_/ / 
 / /  / /  
/_/  /_/ 
```

**Comment by HuangFru** [comment]
> > It feels a little bit strange just for me that the slope of the letter A is not the same as the slope of the other letters.
> 
> The slope of all characters is the same, A will be visually different. 😂
> 
> ```
>     ___ 
>    /   |
>   / /| |
>  / ___ |
> /_/  |_|
>     __  ___
>    /  |/  /
>   / /|_/ / 
>  / /  / /  
> /_/  /_/ 
> ```

Oh..you are right.
What I mean is that visually it looks a little strange that there is a gap between A and M.

**Comment by shidayang** [comment]
Visually, A does look a bit inconsistent. Is there a font style where all the letters are upright?

**Comment by zhongqishang** [comment]
> Visually, A does look a bit inconsistent. Is there a font style where all the letters are upright?

@shidayang @HuangFru 

I found the following two fonts:

Font: Big
Horizontal spacing: Normal
Vertical spacing: Normal 
```                  
           __  __  ____  _____   ____  
     /\   |  \/  |/ __ \|  __ \ / __ \ 
    /  \  | \  / | |  | | |__) | |  | |
   / /\ \ | |\/| | |  | |  _  /| |  | |
  / ____ \| |  | | |__| | | \ \| |__| |
 /_/    \_\_|  |_|\____/|_|  \_\\____/ 
                                       
                                       
```

Font: Standard
Horizontal spacing: Normal
Vertical spacing: Normal 
```
     _    __  __  ___  ____   ___  
    / \  |  \/  |/ _ \|  _ \ / _ \ 
   / _ \ | |\/| | | | | |_) | | | |
  / ___ \| |  | | |_| |  _ <| |_| |
 /_/   \_\_|  |_|\___/|_| \_\\___/ 
                                   
```

**Review by wangtaohz — APPROVED** [review]
```
    ___     __  ___ ____   ____   ____ 
   /   |   /  |/  // __ \ / __ \ / __ \
  / /| |  / /|_/ // / / // /_/ // / / /
 / ___ | / /  / // /_/ // _, _// /_/ / 
/_/  |_|/_/  /_/ \____//_/ |_| \____/  
```
This looks good to me, and coincidentally, the slant of the letter is similar to our logo.
image

**Review by baiyangtx — APPROVED** [review]
LGTM, thanks for your contribution.

**Pull request merged**
