### PR TITLE
[Imporvement]: Add spotless:validate to to all modules

### LINKED ISSUE #1402: [Improvement]: Spotless Maven Plugin Integration
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/arctic/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

I would like to improve the code quality of our project by integrating the Spotless Maven Plugin. This plugin can automatically format our code according to defined rules, ensuring consistency and readability throughout the codebase.

I propose to add the Spotless Maven Plugin to our project's build process and configure it to format our code according to the Arctic Checkstyle. This will help us maintain a clean and consistent codebase, making it easier for developers to understand and modify the code.

Welcome any feedback or suggestions on this proposed improvement.

### How should we improve?

To improve the situation, we could regularly review the Google Java Style Guide and update our code formatting rules accordingly. We could also consider using a tool that automatically updates our code formatting rules based on the latest version of the style guide. Additionally, we could provide training and resources to our developers to ensure they are aware of the latest style guide and understand how to write code that follows it. By staying up-to-date with the latest best practices for code formatting, we can ensure that our code is consistent, readable, and maintainable.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

- https://github.com/NetEase/amoro/issues/2017
- https://github.com/NetEase/amoro/issues/2018
- https://github.com/NetEase/amoro/pull/2108

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by baiyangtx**
## Why are the changes needed?
 
This is a subtask of https://github.com/NetEase/amoro/issues/1402. To replace checkstyle to spotless as default codestyle formatter.

Close #1402.

## Brief change log

- Enable spotless configurations for all modules.
- Remove maven-checkstyle-plugin for all modules.
- Run spotless:apply for all modules.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

### CODE REVIEW

**Comment by wangtaohz** [comment]
After merging this PR, could we use `mvn spotless:check` and `mvn spotless:apply` in the project root location without `-pl`?

**Review by shidayang — APPROVED** [review]

**Comment by zhongqishang** [comment]
We need to modify the `Validate checkstyle first` of the ci yml file. @baiyangtx

**Comment by baiyangtx** [comment]
> We need to modify the `Validate checkstyle first` of the ci yml file. @baiyangtx

How to modify ？

**Comment by baiyangtx** [comment]
> After merging this PR, could we use `mvn spotless:check` and `mvn spotless:apply` in the project root location without `-pl`?

yes we can.

**Comment by zhongqishang** [comment]
> How to modify ？

As describe in #1293, we need to prioritize to checkstyle verification through `mvn validate` -> `mvn spotless:check`.

**Pull request merged**
