### PR TITLE
Rename update.sql file to update-0.5.1-to-0.6.0.sql

### PR DESCRIPTION
**Pull request by shidayang**

### CODE REVIEW

**Review by wangtaohz — COMMENTED** [review]
It should be `upgrade-xxxx` instead of `update-xxx`

**Comment by shidayang** [comment]
> It should be `upgrade-xxxx` instead of `update-xxx`

done

**Comment by zhoujinsong** [comment]
@shidayang We'd better keep the `update.sql` and move the content into the new `uprade-0.5.1-to-0.6.0.sql`.

**Review by wangtaohz — APPROVED** [review]
LGTM

**Comment by shidayang** [comment]
> @shidayang We'd better keep the `update.sql` and move the content into the new `uprade-0.5.1-to-0.6.0.sql`.

Your mean also contain a empty update.sql?

**Review by zhoujinsong — APPROVED** [review]
LGTM.

**Pull request merged**
