### PR TITLE
[DOC] Fixed a counting error

### PR DESCRIPTION
**Pull request by JinsYin**
## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by wangtaohz — COMMENTED** [review]
Thanks for your contribution!

I also found that similar changes need to be made in the `README.md` file. However, the descriptions of table formats in the`docs/formats/overview.md` and `README.md` are different. As the editor of both parts, do you think we should unify the descriptions in these two parts? @zhoujinsong

**Comment by zhoujinsong** [comment]
Yes, the descriptions of these two parts should be the same.

@JinsYin Can you help to modify the `README.md` too?

**Review by baiyangtx — APPROVED** [review]
LGTM

**Comment by wangtaohz** [comment]
It's ok to open another PR to fix the `README.md`.

**Comment by JinsYin** [comment]
@zhoujinsong @wangtaohz I opened another PR to fix it. Please see #2275

**Pull request merged**
