### PR TITLE
[AMORO-2363] Enhance state ctrl in the terminal page

### LINKED ISSUE #2363: [Improvement]: Enhance state ctrl in the terminal page
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

We can not cancel it immediately once a complex sql script is executed. The button(on behalf of Run and Pause) can respond to the click action at any moment which easily causes inconsistent user experience. 
For example, the button can be respond to 'Run' action when 'Pause' action is triggered. But to my surprise, the 'Pause' action is still waiting a response. Unfortunately, we will get an error as follows: 

screenshot-20231126-232829

### How should we improve?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by tcodehuber**
## Why are the changes needed?

Close #2363.

## Brief change log

- change the state ctrl logic of 'Run/Pause' button and 'shortcuts' button
- change param type(sessionId, number-> string) in terminal.service.ts

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by baiyangtx — COMMENTED** [review]
From the code review, it appears that only the front-end code was modified. Has it undergone integration testing? The problem described in the issue seems to be the inability of the back-end to stop the ongoing SQL execution.

**Comment by zhoujinsong** [comment]
@tcodehuber There is a conflict with the master branch, can you fix it?

**Comment by tcodehuber** [comment]
> @tcodehuber There is a conflict with the master branch, can you fix it?

Done, please review it again.

**Review by zhoujinsong — APPROVED** [review]
Validate success in my local envrionment.

**Pull request merged**
