### PR TITLE
[docs] Fix typo for flink optimizer configuration

### PR DESCRIPTION
**Pull request by klion26**
## Why are the changes needed?

Fix typo for flink optimizer configuration

## Brief change log

- fix typos

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

cc @zhoujinsong

### CODE REVIEW

**Review by wangtaohz — APPROVED** [review]
LGTM

**Comment by klion26** [comment]
@wangtaohz thanks for the review and merging!

**Comment by tcodehuber** [comment]
There is the same typo in the document. Can you fix it later? https://github.com/NetEase/amoro/blob/master/docs/admin-guides/deployment-on-kubernetes.md

**Comment by klion26** [comment]
@tcodehuber 
thanks for pointing out this, will file a PR soon.

**Pull request merged**
