### PR TITLE
[AMORO-2373] resolve the catalog problem when querying base on kyuubi+flink

### PR DESCRIPTION
**Pull request by liuzyou6**
when querying used catalog, the syntax is different between FLink and Spark. #2373

### CODE REVIEW

**Review by shidayang — APPROVED** [review]

**Comment by shidayang** [comment]
LGTM

**Comment by wangtaohz** [comment]
Thank you for your contribution, the title should be [AMORO-2373]xxx. 😊

**Review by wangtaohz — APPROVED** [review]
LGTM

**Review by zhoujinsong — APPROVED** [review]
@liuzyou6 Thanks a lot for contribution!

I left some small suggestion, please task a look.

**Comment by zhoujinsong** [comment]
@liuzyou6 Thanks a lot for your contribution!

You may need to sign NetEase's CLA before you start to contribute to Amoro, you can conveniently complete the signing via the link: https://cla-assistant.io/NetEase/amoro

**Pull request merged**
