### PR TITLE
[AMORO-2034] Change `Transactions` page to `Snapshots` page

### LINKED ISSUE #2034: [Subtask]: Display Tags and Branches on the `Transactions` page
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

The display of Tags and Branches in the table can be compared to the way code is managed in GitHub. The `snapshots` of the table are equivalent to `commits` in GitHub. We can switch between different branches and tags to see the snapshots history of each branch or tag.

I drew a diagram to illustrate the new design.

image

As shown above, we make a few adjustments:

1. Change the paga name from `Transactions` to `Snapshots`, as we discussed here #1971 
2. Show all Snapshots, including those generated by optimizing which are displayed like `replace (optimizing)` in the `Operation` column.
3. Support switching between branches and tags.
4. Standardize the content displayed in the line chart and list, by adding a `Records` column and removing the `Size` column.
5. Remove the `Transaction Id` column, which is same as `Snapshot ID`.

Compared to **before** these adjustments:

image

### Parent issue

#1354

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wangtaohz**
## Why are the changes needed?

Close #2034 .

## Brief change log

- change HTTP API from `transactions` to `snapshots`
- add producer, records to the snapshot of HTTP API
- support get all snapshots(optimizing snapshots included)
- support get snapshots of tag/branch (not support on Web UI)
- Web UI change from `Transaction` to `Snapshot` 
- Web UI show the producer of snapshot, like `overwrite(optimizing)`

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (**yes** / no)
- If yes, how is the feature documented? (not applicable / **docs** / JavaDocs / not documented)

### CODE REVIEW

**Comment by wangtaohz** [comment]
The new Web UI after changing

image

**Comment by wangtaohz** [comment]
For Mixed Format, the Web UI also changes to `Snapshots`
image

**Comment by wangtaohz** [comment]
The two filters of WebUI mentioned in the issue #2034  will be completed in this issue #2198 .

**Review by huyuanfeng2018 — APPROVED** [review]
LGTM.

**Comment by zhoujinsong** [comment]
@wangtaohz There are some conflicts we my need to fix.

**Comment by wangtaohz** [comment]
> @wangtaohz There are some conflicts we my need to fix.

Fixed.

**Review by zhoujinsong — APPROVED** [review]
LGTM.

**Comment by tcodehuber** [comment]
LGTM.

**Pull request merged**
