### PR TITLE
[AMORO-1957] Support liveness port testing for standby instance

### PR DESCRIPTION
**Pull request by huyuanfeng2018**
## Why are the changes needed?

Close ##1957

## Brief change log

- Start a thread to open the port for k8s when the container starts k8s use for livenessprobe

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [X] Add screenshots for manual tests if appropriate

In my environment it works fine.

image

- [X] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Review by baiyangtx — COMMENTED** [review]
I think using a separate port as a liveness port is not a good solution. If the goal is to solve the Kubernetes pod liveness probe issue, using the "ps" command is also a viable option. This PR proposes reusing the HTTP port and obtaining the instance status through an HTTP API.

**Comment by wangtaohz** [comment]
> I think using a separate port as a liveness port is not a good solution. If the goal is to solve the Kubernetes pod liveness probe issue, using the "ps" command is also a viable option. This PR proposes reusing the HTTP port and obtaining the instance status through an HTTP API.

Do you think using the HTTP API mentioned here #2082  is a resonable solution?

**Comment by huyuanfeng2018** [comment]
> > I think using a separate port as a liveness port is not a good solution. If the goal is to solve the Kubernetes pod liveness probe issue, using the "ps" command is also a viable option. This PR proposes reusing the HTTP port and obtaining the instance status through an HTTP API.
> 
> Do you think using the HTTP API mentioned here #2082 is a resonable solution? @baiyangtx

Maybe take a look at this:
https://github.com/NetEase/amoro/blob/27bbc6991ce6d495a16527a083f45d89eb1a0268/ams/server/src/main/java/com/netease/arctic/server/dashboard/controller/HealthCheckController.java#L27

**Comment by baiyangtx** [comment]
> > I think using a separate port as a liveness port is not a good solution. If the goal is to solve the Kubernetes pod liveness probe issue, using the "ps" command is also a viable option. This PR proposes reusing the HTTP port and obtaining the instance status through an HTTP API.
> 
> Do you think using the HTTP API mentioned here #2082 is a resonable solution? @baiyangtx

Can this interface be accessed on standby nodes? @wangtaohz

**Comment by wangtaohz** [comment]
> Can this interface be accessed on standby nodes? @wangtaohz

I don't think it can, just like any other HTTP API, only the leader AMS provides HTTP service.

**Comment by baiyangtx** [comment]
Since this PR is not planed to proceed for now, can I close the PR temporarily?  @huyuanfeng2018

**Comment by huyuanfeng2018** [comment]
> Since this PR is not planed to proceed for now, can I close the PR temporarily? @huyuanfeng2018

ok

**Pull request closed without merging**
