### PR TITLE
[Hotfix] Remove dependency log4j:1.2.17 and exclude logback

### PR DESCRIPTION
**Pull request by zhongqishang**
## Why are the changes needed?

Remove dependency log4j:1.2.17 and modify test log level

## Brief change log

- Remove dependency log4j:1.2.17
- Modify test log level

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by zhongqishang** [comment]
Excluding debug logs, CI logs 50m -> 20m
image

**Comment by zhoujinsong** [comment]
> Excluding debug logs, CI logs 50m -> 20m 

Good job, this is a great improvement about the ci logs.
But I am not sure what is the reason these DEBUG logs is not printed again.

I excluded the logback pakacges in #2583 as you did and I found the ci logs is quite smaller too.

**Comment by zhongqishang** [comment]
@zhoujinsong 

> It seems some test codes use logback as it's logger and print many DEBUG logs.

Yes, what really takes effect is `logback`. If no logback configuration is found, it takes effect by default at `DEBUG` level.

I think this small pr can merge to #2583

**Comment by zhongqishang** [comment]
And debug log of `org.apache.hc.client5.http.headers` can be turned on in the PR if needed, and daily CI should remain in the INFO, WDYT .

**Comment by zhoujinsong** [comment]
> think this small pr can merge to #25863

I prefer merging this PR first, and you can exclude the logback packages here.

> And debug log of `org.apache.hc.client5.http.headers` can be turned on in the PR if needed, and daily CI should remain in the INFO, WDYT .

I think we should keep the `org.apache.hc.client5.http.headers` logger in debug mode as it print some useful HTTP informartions.

**Review by zhoujinsong — APPROVED** [review]
LGTM.
Thanks a lot for your contribution!

**Pull request merged**
