### PR TITLE
fix: resolve svg component & auto import antd-vue component, style & …

### PR DESCRIPTION
**Pull request by zhangmo8**
## Why are the changes needed?

resolve the `svg-vue` component 

auto import antd-vue component that with style

make up `apache` license on any file

generate license script

截屏2023-12-21 22 53 59

Close #xxx.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by wangtaohz** [comment]
Thanks for you contribution 👍 @zhangmo8 
I test it locally after `pnpm build`, and it looks good. Can you build and push the static files in this PR?

image
image
image

**Comment by wangtaohz** [comment]
Additionally, I noticed there is a difference in the font color compared to before; the current color seems a bit darker. Is this as expected?

before
image

after
image

**Comment by zhangmo8** [comment]
> Thanks for you contribution 👍 @zhangmo8 
> 
> I test it locally after `pnpm build`, and it looks good. Can you build and push the static files in this PR?
> 
> 
> 
> image
> 
> image
> 
> image
> 
> 

OK. I will be update the static file when I arrive home

**Comment by zhangmo8** [comment]
> Additionally, I noticed there is a difference in the font color compared to before; the current color seems a bit darker. Is this as expected?
> 
> 
> 
> before
> 
> image
> 
> 
> 
> after
> 
> image
> 
> 

It's expected. I update the Antd-vue to 3.x lastly.

**Review by zhoujinsong — APPROVED** [review]
LGTM.

**Pull request merged**
