### PR TITLE
[AMORO-2149]: Add filter select by optimizeGroup for Optimize Table

### LINKED ISSUE #2149: [Subtask]: Support filter for `Optimizer Group` column of Optimizing Tables page
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### Description

Support filter for this `Optimizer Group` column of Optimizing Tables page would bring convenience to users who use multiple optimizer groups.

image

### Parent issue

#885

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhangmo8**
## Why are the changes needed?

Add filter select by optimizeGroup for Optimize Table

image

Close #2149.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by songjianet — APPROVED** [review]

**Comment by zhoujinsong** [comment]
@zhangmo8 Thanks a lot for your work!

However, considering that we will be adding more filters on additional fields in the table in the future, would it be more appropriate to add a filter icon in the table header for filtering operations?

Of course, this requires your assistance in assessing its feasibility for implementation.
I understand that adding sorting, filtering, and searching on specific table fields may be a potential requirement in the future.

**Comment by zhangmo8** [comment]
> @zhangmo8 Thanks a lot for your work!
> 
> However, considering that we will be adding more filters on additional fields in the table in the future, would it be more appropriate to add a filter icon in the table header for filtering operations?
> 
> Of course, this requires your assistance in assessing its feasibility for implementation. I understand that adding sorting, filtering, and searching on specific table fields may be a potential requirement in the future.

It is true that adding filter items to the table header is actually easier for building the front end, but I personally think that using a selection box outside is more in line with the existing operation interaction. @zhoujinsong

**Comment by zhoujinsong** [comment]
Yes, I have also noticed that some pages now have additional selectors to filter page content, such as selecting partitions on the `Files` page in the table details and selecting operations on the `Snapshots` page.

Perhaps we should establish a unified interaction method and strive for consistency in both new and old implementations. In my opinion, I still advocate for adding filters in the table headers, as this would allow us to add filters to more columns. Having separate filters can appear cluttered when there is a need to filter a lot of content.

**Comment by zhoujinsong** [comment]
After discussing offline with @zhangmo8 @minteliuwm , we reached an agreement:

- Place the filtering and searching component above the table rather than in the header, making it easier for users to see the current filtering status.
- Place the sorting component directly in the table header.

All similar interaction requirements in the future should follow this guideline.

**Review by zhoujinsong — APPROVED** [review]
I tested it in my local environment and it works fine.

**Pull request merged**
