### PR TITLE
[AMORO-1839] Removed `SequenceNumberFetcher ` related codes

### PR DESCRIPTION
**Pull request by huyuanfeng2018**
## Why are the changes needed?

Relate to  #1839

## Brief change log
Removed `SequenceNumberFetcher.java`, directly use `org.apache.iceberg.ContentFile#dataSequenceNumber` to fetch SequenceNumber

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [X] Run test locally before making a pull request

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by baiyangtx — APPROVED** [review]
LGTM.
Thank you for submitting your Pull Request, your contribution is greatly appreciated!

**Comment by zhoujinsong** [comment]
@huyuanfeng2018 Do you think we can replace `com.netease.arctic.data.IcebergDataFile` with `org.apache.iceberg.DateFile` directly?

The same to `com.netease.arctic.data.IcebergDeleteFile` and `com.netease.arctic.data.IcebergContentFile`.

**Comment by huyuanfeng2018** [comment]
I did not remove `IcebergContentFile`, because `IcebergContentFile` seems to have undertaken other tasks, and it may be necessary to completely delete `IcebergContentFile` in other issues, this pr is mainly to solve the problem of `SequenceNumberFetcher`

**Comment by baiyangtx** [comment]
I think after upgrading to Iceberg 1.3, the entire `IcebergContentFile` interface, including `IcebergDataFile `and `IcebergDeleteFile`, may no longer be needed as their purpose is to encapsulate Iceberg files and sequence number, which can now be obtained directly from` ContentFile.dataSequenceNumber()`. 

However, since removing these classes would be a huge job, I suggest removing them in other PRs

**Comment by huyuanfeng2018** [comment]
> I think after upgrading to Iceberg 1.3, the entire `IcebergContentFile` interface, including `IcebergDataFile `and `IcebergDeleteFile`, may no longer be needed as their purpose is to encapsulate Iceberg files and sequence number, which can now be obtained directly from` ContentFile.dataSequenceNumber()`.
> 
> However, since removing these classes would be a huge job, I suggest removing them in other PRs

+1

**Comment by zhoujinsong** [comment]
Sure, we can remove these classes in another PR.

As for the serialization incompatibility issue caused during the upgrade, my idea is to clean up the information of the unfinished self-optimizing process in the upgrade SQL script, which will result in the loss of unfinished process information during the upgrade, but I think this is acceptable.

**Comment by huyuanfeng2018** [comment]
> Sure, we can remove these classes in another PR.
> 
> As for the serialization incompatibility issue caused during the upgrade, my idea is to clean up the information of the unfinished self-optimizing process in the upgrade SQL script, which will result in the loss of unfinished process information during the upgrade, but I think this is acceptable.

We recommend that the cleanup script be written into the official documentation

**Review by shidayang — APPROVED** [review]

**Comment by shidayang** [comment]
LGTM

**Comment by zhoujinsong** [comment]
> > Sure, we can remove these classes in another PR.
> > As for the serialization incompatibility issue caused during the upgrade, my idea is to clean up the information of the unfinished self-optimizing process in the upgrade SQL script, which will result in the loss of unfinished process information during the upgrade, but I think this is acceptable.
> 
> We recommend that the cleanup script be written into the official documentation

Sure.

**Comment by huyuanfeng2018** [comment]
> As this PR didn't completely remove the classes related to IcebergContentFile, #1839 cannot be closed yet.

ok, I will finish this part

**Pull request merged**
