### PR TITLE
[AMORO-2565] Optimization task loss leads to the optimization process remaining in a running state indefinitely

### LINKED ISSUE #2565: [Bug]: Optimization task loss leads to the optimization process remaining in a running state indefinitely
### What happened?

Task-14 does not exist in the `taskQueue` of AMS, so this task remains in the planned state.
uTools_1708763128753

The root cause of this bug is that even if `retryTaskQueue.poll()` returns a task,`fetchScheduledTask()` will still be called as usual. Once `fetchScheduledTask()` also fetches a task, this task will be lost. 
uTools_1708764475759

### Affects Versions

master

### What engines are you seeing the problem on?

AMS

### Relevant log output

uTools_1708765703735

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rfyu**
## Why are the changes needed?

Close #2565.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not documented)

### CODE REVIEW

**Comment by huyuanfeng2018** [comment]
Can add some test cases?

**Comment by rfyu** [comment]
> Can add some test cases?

This change is relatively simple, but I don't know how to write concurrent tests. This scenario only occurs when polling task from multiple tables in the same `OptimizingQueue` simultaneously.

**Comment by huyuanfeng2018** [comment]
> > Can add some test cases?
> 
> This change is relatively simple, but I don't know how to write concurrent tests. This scenario only occurs when polling task from multiple tables in the same `OptimizingQueue` simultaneously.

I couldn't reproduce this bug  locally. The main reason is that after this modification, If the `clearProcess` method is not called, it seems that we cannot make the tasks of other tables enter the optmizer.

**Comment by rfyu** [comment]
> > > Can add some test cases?
> > 
> > 
> > This change is relatively simple, but I don't know how to write concurrent tests. This scenario only occurs when polling task from multiple tables in the same `OptimizingQueue` simultaneously.
> 
> I couldn't reproduce this bug locally. The main reason is that after this modification, If the `clearProcess` method is not called, it seems that we cannot make the tasks of other tables enter the optmizer.

You are right, my modification is wrong.

**Pull request closed without merging**
