### PR TITLE
[AMORO-2369]Optimize project module structure

### LINKED ISSUE #2369: [Improvement]: Optimize the project's module structure
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The current module structure of the project does not effectively reflect the hierarchical relationship between modules, often leading to incorrect guidance for developers who are new to the code. 

We need to optimize the existing module structure to make it more logical and assist developers in understanding the roles of different modules correctly.

### How should we improve?

The module adjustment this time does not involve introducing new modules or moving classes to other modules. It will only involve reorganizing the existing modules to truly reflect their hierarchical structure.

The new module structure will be:
```
- core
- ams
  - api
  - server
  - dashboard
  - optimizer
    - common
    - flink-optimizer
    - standalone-optimizer
  - dist 
- mixed
  - flink
    - flink-common
    - flink-common-format
    - flink-common-iceberg-bridge
    - v1.15/flink
    - v1.15/flink-runtime
    - v1.16/flink
    - v1.16/flink-runtime
    - v1.17/flink
    - v1.17/flink-runtime
  - spark
    - common
    - v3.1/spark
    - v3.1/spark-runtime
    - v3.2/spark
    - v3.2/spark-runtime
    - v3.3/spark
    - v3.3/spark-runtime
  - hive
  - trino
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhoujinsong**
## Why are the changes needed?

Close #2369 .

## Brief change log

- Restructure project modules.
- Change docs due to the module change.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by zhoujinsong** [comment]
The rename operation will not conflict with other line changes, so it is safe to merge this PR even through the File Changes is quite large.

**Review by baiyangtx — COMMENTED** [review]
1. Why haven't the parts related to core and mixed-format been moved to the mixed module? 
2. Regarding the unified catalog section, is a separate module needed?

**Review by baiyangtx — COMMENTED** [review]
The PR #2269 is introducing the UnifiedCatalog implementation on the Spark engine side, which will create massive conflicts with this PR. 
I suggest merging the engine-side implementation first before proceeding with this matter.

**Comment by zhoujinsong** [comment]
> 1. Why haven't the parts related to core and mixed-format been moved to the mixed module?
These tasks are indeed necessary, however, this PR will not introduce new modules or move classes to other modules. Maybe we can complete these tasks with other PRs.

> 2. Regarding the unified catalog section, is a separate module needed?
I think so.

**Comment by zhoujinsong** [comment]
> The PR #2269 is introducing the UnifiedCatalog implementation on the Spark engine side, which will create massive conflicts with this PR. I suggest merging the engine-side implementation first before proceeding with this matter.

As I mentioned above, the rename operation will not conflict with other line changes. However, considering that #2269 may introduce new classes, these new classes might create conflicts. Nevertheless, such conflicts should be relatively easy to resolve.

I am uncertain about when #2269 can be merged, so I suggest that this PR not wait for the merge of #2269.

**Review by baiyangtx — APPROVED** [review]
LGTM, we can extract UnifiedCatalog and rename package in another PR

**Pull request merged**
